package com.tuck.app

import android.content.Context
import android.content.Intent
import androidx.work.WorkManager
import com.tuck.app.data.local.storage.FileStorageService
import com.tuck.app.data.local.storage.StorageSaveResult
import com.tuck.app.domain.model.Collection
import com.tuck.app.domain.model.ContentType
import com.tuck.app.domain.model.SavedItem
import com.tuck.app.domain.repository.CollectionRepository
import com.tuck.app.domain.repository.SavedItemRepository
import com.tuck.app.processing.DuplicateDetector
import com.tuck.app.processing.ParsedShareContent
import com.tuck.app.processing.ShareParser
import com.tuck.app.processing.UrlMetadataProcessor
import com.tuck.app.ui.share.ShareUiState
import com.tuck.app.ui.share.ShareViewModel
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkStatic
import io.mockk.unmockkStatic
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class ShareViewModelTest {

    private val testDispatcher = StandardTestDispatcher()

    private val context: Context = mockk(relaxed = true)
    private val shareParser: ShareParser = mockk(relaxed = true)
    private val savedItemRepository: SavedItemRepository = mockk(relaxed = true)
    private val collectionRepository: CollectionRepository = mockk(relaxed = true)
    private val fileStorageService: FileStorageService = mockk(relaxed = true)
    private val duplicateDetector: DuplicateDetector = mockk(relaxed = true)
    private val urlMetadataProcessor: UrlMetadataProcessor = mockk(relaxed = true)
    private val workManager: WorkManager = mockk(relaxed = true)

    private lateinit var viewModel: ShareViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        every { context.applicationContext } returns context

        coEvery { collectionRepository.ensureDefaultCollections() } returns Unit
        coEvery { collectionRepository.getAllCollections() } returns flowOf(
            listOf(
                Collection(id = 1L, name = "Articles", isAutoGenerated = true),
                Collection(id = 2L, name = "Programming", isAutoGenerated = true)
            )
        )

        viewModel = ShareViewModel(
            shareParser = shareParser,
            savedItemRepository = savedItemRepository,
            collectionRepository = collectionRepository,
            fileStorageService = fileStorageService,
            duplicateDetector = duplicateDetector,
            urlMetadataProcessor = urlMetadataProcessor,
            workManager = workManager,
            ioDispatcher = testDispatcher
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    @Test
    fun testHandleIncomingIntentSuccess() = runTest(testDispatcher) {
        val intent = mockk<Intent>(relaxed = true)
        val parsed = ParsedShareContent(
            contentType = ContentType.URL,
            title = "Kotlin Multiplatform Guide",
            url = "https://kotlinlang.org/docs/multiplatform.html",
            sourceApp = "com.android.chrome"
        )

        every { shareParser.parseIntent(intent, any()) } returns parsed
        every { duplicateDetector.getCanonicalUrl(any()) } returns "https://kotlinlang.org/docs/multiplatform.html"
        every { urlMetadataProcessor.extractDomain(any()) } returns "kotlinlang.org"
        coEvery { savedItemRepository.insertItem(any()) } returns 101L

        viewModel.handleIncomingIntent(intent, "com.android.chrome")
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertTrue(state is ShareUiState.Saved)
        val savedState = state as ShareUiState.Saved
        assertEquals(101L, savedState.savedItemId)
        assertEquals("Kotlin Multiplatform Guide", savedState.title)
        assertEquals(2, savedState.collections.size)

        coVerify(exactly = 1) { savedItemRepository.insertItem(match { it.title == "Kotlin Multiplatform Guide" && it.contentType == ContentType.URL }) }
        coVerify(exactly = 1) { workManager.enqueue(any<androidx.work.WorkRequest>()) }
    }

    @Test
    fun testHandleIncomingIntentWithInvalidContentShowsError() = runTest(testDispatcher) {
        val intent = mockk<Intent>(relaxed = true)
        every { shareParser.parseIntent(intent, any()) } returns null

        viewModel.handleIncomingIntent(intent, null)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertTrue(state is ShareUiState.Error)
    }

    @Test
    fun testToggleCollectionAddsAndRemoves() = runTest(testDispatcher) {
        val intent = mockk<Intent>(relaxed = true)
        val parsed = ParsedShareContent(
            contentType = ContentType.TEXT,
            title = "Quick Note",
            text = "Testing note"
        )
        every { shareParser.parseIntent(intent, any()) } returns parsed
        coEvery { savedItemRepository.insertItem(any()) } returns 50L

        viewModel.handleIncomingIntent(intent, null)
        advanceUntilIdle()

        // Toggle add collection 1
        viewModel.toggleCollection(1L)
        advanceUntilIdle()

        var savedState = viewModel.uiState.value as ShareUiState.Saved
        assertTrue(savedState.selectedCollectionIds.contains(1L))
        coVerify(exactly = 1) { savedItemRepository.addItemToCollection(50L, 1L) }

        // Toggle remove collection 1
        viewModel.toggleCollection(1L)
        advanceUntilIdle()

        savedState = viewModel.uiState.value as ShareUiState.Saved
        assertTrue(!savedState.selectedCollectionIds.contains(1L))
        coVerify(exactly = 1) { savedItemRepository.removeItemFromCollection(50L, 1L) }
    }

    @Test
    fun testCreateAndAddCollection() = runTest(testDispatcher) {
        val intent = mockk<Intent>(relaxed = true)
        val parsed = ParsedShareContent(
            contentType = ContentType.TEXT,
            title = "Recipe Note",
            text = "Pasta recipe"
        )
        every { shareParser.parseIntent(intent, any()) } returns parsed
        coEvery { savedItemRepository.insertItem(any()) } returns 77L
        coEvery { collectionRepository.createCollection("Recipes", false) } returns 10L

        viewModel.handleIncomingIntent(intent, null)
        advanceUntilIdle()

        viewModel.createAndAddCollection("Recipes")
        advanceUntilIdle()

        coVerify(exactly = 1) { collectionRepository.createCollection("Recipes", false) }
        coVerify(exactly = 1) { savedItemRepository.addItemToCollection(77L, 10L) }
    }
}
