package com.tuck.app.di

import android.content.Context
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.tuck.app.data.local.db.TuckDatabase
import com.tuck.app.data.local.db.dao.CollectionDao
import com.tuck.app.data.local.db.dao.DerivedContentDao
import com.tuck.app.data.local.db.dao.EntityDao
import com.tuck.app.data.local.db.dao.ItemRawPayloadDao
import com.tuck.app.data.local.db.dao.MediaAssetDao
import com.tuck.app.data.local.db.dao.SavedItemDao
import com.tuck.app.data.local.db.dao.SavedItemFtsDao
import com.tuck.app.data.local.db.dao.SavedItemFtsDaoImpl
import com.tuck.app.data.local.db.dao.SearchHistoryDao
import com.tuck.app.data.local.db.dao.SourceContentDao
import com.tuck.app.data.local.db.dao.TagDao
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import javax.inject.Provider
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    @Provides
    @Singleton
    fun provideTuckDatabase(
        @ApplicationContext context: Context,
        collectionDaoProvider: Provider<CollectionDao>
    ): TuckDatabase {
        return Room.databaseBuilder(
            context,
            TuckDatabase::class.java,
            TuckDatabase.DATABASE_NAME
        ).addCallback(object : RoomDatabase.Callback() {
            override fun onCreate(db: SupportSQLiteDatabase) {
                super.onCreate(db)
                // The FTS5 index is not a Room entity, so Room will not create it
                // on a fresh install - only MIGRATION_3_4 covers upgrades.
                db.execSQL(SavedItemFtsDaoImpl.CREATE_TABLE)
                db.execSQL(SavedItemFtsDaoImpl.CREATE_DELETE_TRIGGER)
                CoroutineScope(Dispatchers.IO).launch {
                    val dao = collectionDaoProvider.get()
                    for ((name, icon) in TuckDatabase.DEFAULT_SMART_COLLECTIONS) {
                        dao.insert(
                            com.tuck.app.data.local.db.entity.CollectionEntity(
                                name = name,
                                isAutoGenerated = true,
                                icon = icon
                            )
                        )
                    }
                }
            }
        }).addMigrations(
            TuckDatabase.MIGRATION_1_2,
            TuckDatabase.MIGRATION_2_3,
            TuckDatabase.MIGRATION_3_4
        )
            .build()
    }

    @Provides
    fun provideSavedItemDao(database: TuckDatabase): SavedItemDao = database.savedItemDao()

    @Provides
    fun provideSavedItemFtsDao(database: TuckDatabase): SavedItemFtsDao = SavedItemFtsDaoImpl(database)

    @Provides
    fun provideEntityDao(database: TuckDatabase): EntityDao = database.entityDao()

    @Provides
    fun provideTagDao(database: TuckDatabase): TagDao = database.tagDao()

    @Provides
    fun provideCollectionDao(database: TuckDatabase): CollectionDao = database.collectionDao()

    @Provides
    fun provideSearchHistoryDao(database: TuckDatabase): SearchHistoryDao = database.searchHistoryDao()

    @Provides
    fun provideMediaAssetDao(database: TuckDatabase): MediaAssetDao = database.mediaAssetDao()

    @Provides
    fun provideSourceContentDao(database: TuckDatabase): SourceContentDao = database.sourceContentDao()

    @Provides
    fun provideDerivedContentDao(database: TuckDatabase): DerivedContentDao = database.derivedContentDao()

    @Provides
    fun provideItemRawPayloadDao(database: TuckDatabase): ItemRawPayloadDao = database.itemRawPayloadDao()
}
