package com.tuck.app.data.repository

import com.tuck.app.data.local.db.TuckDatabase
import com.tuck.app.data.local.db.dao.CollectionDao
import com.tuck.app.data.local.db.entity.CollectionEntity
import com.tuck.app.domain.model.Collection
import com.tuck.app.domain.repository.CollectionRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import com.tuck.app.data.local.db.dao.CollectionWithCount
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CollectionRepositoryImpl @Inject constructor(
    private val collectionDao: CollectionDao
) : CollectionRepository {

    private companion object {
        /** Three reads as a composition; four starts to look like a contact sheet. */
        const val PREVIEWS_PER_COLLECTION = 3
    }



    /** Attaches preview images to any collection flow, so every surface gets them. */
    private fun Flow<List<CollectionWithCount>>.withPreviews(): Flow<List<Collection>> =
        combine(collectionDao.getCollectionPreviews(PREVIEWS_PER_COLLECTION)) { list, previews ->
            val byCollection = previews.groupBy { it.collectionId }
            list.map { row ->
                Collection(
                    id = row.id,
                    name = row.name,
                    isAutoGenerated = row.isAutoGenerated,
                    icon = row.icon,
                    color = row.color,
                    isLocked = row.isLocked,
                    itemCount = row.itemCount,
                    openCount = row.openCount,
                    previewPaths = byCollection[row.id].orEmpty().map { it.path },
                    createdAt = row.createdAt
                )
            }
        }

    override fun getAllCollections(): Flow<List<Collection>> =
        collectionDao.getAllCollectionsWithCount().withPreviews()

    override fun getAutoGeneratedCollections(): Flow<List<Collection>> =
        collectionDao.getAutoGeneratedCollectionsWithCount().withPreviews()

    override fun getCustomCollections(): Flow<List<Collection>> =
        collectionDao.getCustomCollectionsWithCount().withPreviews()

    override suspend fun getCollectionById(id: Long): Collection? = withContext(Dispatchers.IO) {
        val entity = collectionDao.getById(id) ?: return@withContext null
        Collection(
            id = entity.id,
            name = entity.name,
            isAutoGenerated = entity.isAutoGenerated,
            icon = entity.icon,
            color = entity.color,
            isLocked = entity.isLocked,
            createdAt = entity.createdAt
        )
    }

    override suspend fun getCollectionByName(name: String): Collection? = withContext(Dispatchers.IO) {
        val entity = collectionDao.getByName(name) ?: return@withContext null
        Collection(
            id = entity.id,
            name = entity.name,
            isAutoGenerated = entity.isAutoGenerated,
            icon = entity.icon,
            color = entity.color,
            isLocked = entity.isLocked,
            createdAt = entity.createdAt
        )
    }

    override suspend fun createCollection(name: String, isAutoGenerated: Boolean, icon: String?, color: String?): Long = withContext(Dispatchers.IO) {
        collectionDao.insert(
            CollectionEntity(
                name = name.trim(),
                isAutoGenerated = isAutoGenerated,
                icon = icon,
                color = color
            )
        )
    }

    override suspend fun updateCollectionColor(id: Long, color: String?) = withContext(Dispatchers.IO) {
        val existing = collectionDao.getById(id)
        if (existing != null) {
            collectionDao.update(existing.copy(color = color))
        }
    }

    override suspend fun renameCollection(id: Long, newName: String) = withContext(Dispatchers.IO) {
        val existing = collectionDao.getById(id)
        if (existing != null) {
            collectionDao.update(existing.copy(name = newName.trim()))
        }
    }

    override suspend fun deleteCollection(id: Long) = withContext(Dispatchers.IO) {
        collectionDao.deleteCollection(id)
    }

    override suspend fun ensureDefaultCollections() = withContext(Dispatchers.IO) {
        for ((name, icon) in TuckDatabase.DEFAULT_SMART_COLLECTIONS) {
            val existing = collectionDao.getByName(name)
            if (existing == null) {
                collectionDao.insert(
                    CollectionEntity(
                        name = name,
                        isAutoGenerated = true,
                        icon = icon
                    )
                )
            }
        }
    }
}
