package com.tuck.app.data.repository

import com.tuck.app.data.local.db.TuckDatabase
import com.tuck.app.data.local.db.dao.CollectionDao
import com.tuck.app.data.local.db.entity.CollectionEntity
import com.tuck.app.domain.model.Collection
import com.tuck.app.domain.repository.CollectionRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CollectionRepositoryImpl @Inject constructor(
    private val collectionDao: CollectionDao
) : CollectionRepository {

    override fun getAllCollections(): Flow<List<Collection>> {
        return collectionDao.getAllCollectionsWithCount().map { list ->
            list.map {
                Collection(
                    id = it.id,
                    name = it.name,
                    isAutoGenerated = it.isAutoGenerated,
                    icon = it.icon,
                    itemCount = it.itemCount,
                    createdAt = it.createdAt
                )
            }
        }
    }

    override fun getAutoGeneratedCollections(): Flow<List<Collection>> {
        return collectionDao.getAutoGeneratedCollectionsWithCount().map { list ->
            list.map {
                Collection(
                    id = it.id,
                    name = it.name,
                    isAutoGenerated = it.isAutoGenerated,
                    icon = it.icon,
                    itemCount = it.itemCount,
                    createdAt = it.createdAt
                )
            }
        }
    }

    override fun getCustomCollections(): Flow<List<Collection>> {
        return collectionDao.getCustomCollectionsWithCount().map { list ->
            list.map {
                Collection(
                    id = it.id,
                    name = it.name,
                    isAutoGenerated = it.isAutoGenerated,
                    icon = it.icon,
                    itemCount = it.itemCount,
                    createdAt = it.createdAt
                )
            }
        }
    }

    override suspend fun getCollectionById(id: Long): Collection? = withContext(Dispatchers.IO) {
        val entity = collectionDao.getById(id) ?: return@withContext null
        Collection(
            id = entity.id,
            name = entity.name,
            isAutoGenerated = entity.isAutoGenerated,
            icon = entity.icon,
            createdAt = entity.createdAt
        )
    }

    override suspend fun getCollectionByName(name: String): Collection? = withContext(Dispatchers.IO) {
        val entity = collectionDao.getByName(name) ?: return@withContext null
        Collection(
            id = entity.id,
            name = entity.name,
            isAutoGenerated = entity.isAutoGenerated,
            icon = entity.icon,
            createdAt = entity.createdAt
        )
    }

    override suspend fun createCollection(name: String, isAutoGenerated: Boolean, icon: String?): Long = withContext(Dispatchers.IO) {
        collectionDao.insert(
            CollectionEntity(
                name = name.trim(),
                isAutoGenerated = isAutoGenerated,
                icon = icon
            )
        )
    }

    override suspend fun renameCollection(id: Long, newName: String) = withContext(Dispatchers.IO) {
        val existing = collectionDao.getById(id)
        if (existing != null) {
            collectionDao.update(existing.copy(name = newName.trim()))
        }
    }

    override suspend fun deleteCollection(id: Long) = withContext(Dispatchers.IO) {
        collectionDao.deleteCollection(id)
    }

    override suspend fun ensureDefaultCollections() = withContext(Dispatchers.IO) {
        val count = collectionDao.getCollectionCount()
        if (count == 0) {
            for ((name, icon) in TuckDatabase.DEFAULT_SMART_COLLECTIONS) {
                collectionDao.insert(
                    CollectionEntity(
                        name = name,
                        isAutoGenerated = true,
                        icon = icon
                    )
                )
            }
        }
    }
}
