package com.tuck.app.data.repository

import com.tuck.app.data.local.db.dao.CollectionDao
import com.tuck.app.data.local.db.dao.EntityDao
import com.tuck.app.data.local.db.dao.SavedItemDao
import com.tuck.app.data.local.db.dao.SavedItemFtsDao
import com.tuck.app.data.local.db.dao.TagDao
import com.tuck.app.data.local.db.entity.SavedItemCollectionCrossRef
import com.tuck.app.data.local.db.entity.SavedItemEntity
import com.tuck.app.data.local.db.entity.SavedItemFtsEntity
import com.tuck.app.data.local.storage.FileStorageService
import com.tuck.app.domain.model.Collection
import com.tuck.app.domain.model.ContentType
import com.tuck.app.domain.model.ExtractedEntity
import com.tuck.app.domain.model.ProcessingStatus
import com.tuck.app.domain.model.SavedComment
import com.tuck.app.domain.model.SavedItem
import com.tuck.app.domain.model.Tag
import com.tuck.app.domain.repository.SavedItemRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SavedItemRepositoryImpl @Inject constructor(
    private val savedItemDao: SavedItemDao,
    private val savedItemFtsDao: SavedItemFtsDao,
    private val entityDao: EntityDao,
    private val tagDao: TagDao,
    private val collectionDao: CollectionDao,
    private val fileStorageService: FileStorageService
) : SavedItemRepository {

    override fun getAllActiveItems(): Flow<List<SavedItem>> {
        return savedItemDao.getAllActiveItems().map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getRecentItems(limit: Int): Flow<List<SavedItem>> {
        return savedItemDao.getRecentItems(limit).map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getFavoriteItems(): Flow<List<SavedItem>> {
        return savedItemDao.getFavoriteItems().map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getArchivedItems(): Flow<List<SavedItem>> {
        return savedItemDao.getArchivedItems().map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getTrashedItems(): Flow<List<SavedItem>> {
        return savedItemDao.getTrashedItems().map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getItemsByType(contentType: ContentType): Flow<List<SavedItem>> {
        return savedItemDao.getItemsByType(contentType).map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getItemsByCollection(collectionId: Long): Flow<List<SavedItem>> {
        return savedItemDao.getItemsByCollection(collectionId).map { list ->
            list.map { it.toDomain() }
        }
    }

    override fun getItemByIdFlow(id: Long): Flow<SavedItem?> {
        return savedItemDao.getItemByIdFlow(id).map { entity ->
            entity?.let { loadFullItem(it) }
        }
    }

    override suspend fun getItemById(id: Long): SavedItem? = withContext(Dispatchers.IO) {
        val entity = savedItemDao.getItemById(id) ?: return@withContext null
        loadFullItem(entity)
    }

    private suspend fun loadFullItem(entity: SavedItemEntity): SavedItem {
        val entities = entityDao.getEntitiesForItem(entity.id).map {
            ExtractedEntity(
                id = it.id,
                savedItemId = it.savedItemId,
                type = it.type,
                value = it.value,
                normalizedValue = it.normalizedValue
            )
        }
        val tags = tagDao.getTagsForSavedItem(entity.id).map {
            Tag(id = it.id, name = it.name)
        }
        val collections = collectionDao.getCollectionsForSavedItem(entity.id).map {
            Collection(
                id = it.id,
                name = it.name,
                isAutoGenerated = it.isAutoGenerated,
                icon = it.icon,
                createdAt = it.createdAt
            )
        }
        return entity.toDomain(entities = entities, tags = tags, collections = collections)
    }

    override suspend fun insertItem(item: SavedItem): Long = withContext(Dispatchers.IO) {
        val entity = SavedItemEntity(
            id = item.id,
            contentType = item.contentType,
            title = item.title,
            description = item.description,
            originalUrl = item.originalUrl,
            canonicalUrl = item.canonicalUrl,
            sourceDomain = item.sourceDomain,
            sourceApp = item.sourceApp,
            mimeType = item.mimeType,
            localFilePath = item.localFilePath,
            thumbnailPath = item.thumbnailPath,
            originalText = item.originalText,
            extractedText = item.extractedText,
            ocrText = item.ocrText,
            createdAt = item.createdAt,
            updatedAt = item.updatedAt,
            lastOpenedAt = item.lastOpenedAt,
            isFavorite = item.isFavorite,
            isPinned = item.isPinned,
            isArchived = item.isArchived,
            isDeleted = item.isDeleted,
            processingStatus = item.processingStatus,
            userNote = item.userNote,
            captureNote = item.captureNote
        )
        val generatedId = savedItemDao.insert(entity)

        // Seed initial FTS entry
        val fts = SavedItemFtsEntity(
            rowid = generatedId,
            title = item.title,
            description = item.description.orEmpty(),
            originalUrl = item.originalUrl.orEmpty(),
            sourceDomain = item.sourceDomain.orEmpty(),
            originalText = item.originalText.orEmpty(),
            extractedText = item.extractedText.orEmpty(),
            ocrText = item.ocrText.orEmpty(),
            tags = "",
            entities = ""
        )
        savedItemFtsDao.insertOrUpdate(fts)

        generatedId
    }

    override suspend fun updateItem(item: SavedItem): Unit = withContext(Dispatchers.IO) {
        val entity = SavedItemEntity(
            id = item.id,
            contentType = item.contentType,
            title = item.title,
            description = item.description,
            originalUrl = item.originalUrl,
            canonicalUrl = item.canonicalUrl,
            sourceDomain = item.sourceDomain,
            sourceApp = item.sourceApp,
            mimeType = item.mimeType,
            localFilePath = item.localFilePath,
            thumbnailPath = item.thumbnailPath,
            originalText = item.originalText,
            extractedText = item.extractedText,
            ocrText = item.ocrText,
            createdAt = item.createdAt,
            updatedAt = System.currentTimeMillis(),
            lastOpenedAt = item.lastOpenedAt,
            isFavorite = item.isFavorite,
            isPinned = item.isPinned,
            isArchived = item.isArchived,
            isDeleted = item.isDeleted,
            processingStatus = item.processingStatus,
            userNote = item.userNote,
            captureNote = item.captureNote
        )
        savedItemDao.update(entity)

        val fts = SavedItemFtsEntity(
            rowid = item.id,
            title = item.title,
            description = item.description.orEmpty(),
            originalUrl = item.originalUrl.orEmpty(),
            sourceDomain = item.sourceDomain.orEmpty(),
            originalText = item.originalText.orEmpty(),
            extractedText = item.extractedText.orEmpty(),
            ocrText = item.ocrText.orEmpty(),
            tags = item.tags.joinToString(" ") { it.name },
            entities = item.entities.joinToString(" ") { it.value }
        )
        savedItemFtsDao.insertOrUpdate(fts)
    }

    override suspend fun updateProcessingStatus(
        id: Long,
        status: ProcessingStatus,
        ocrText: String?,
        extractedText: String?,
        title: String?,
        description: String?
    ) = withContext(Dispatchers.IO) {
        savedItemDao.updateProcessingResult(
            id = id,
            status = status,
            ocrText = ocrText,
            extractedText = extractedText,
            title = title,
            description = description
        )
    }

    override suspend fun setFavorite(id: Long, isFavorite: Boolean) = withContext(Dispatchers.IO) {
        savedItemDao.setFavorite(id, isFavorite)
    }

    override suspend fun setArchived(id: Long, isArchived: Boolean) = withContext(Dispatchers.IO) {
        savedItemDao.setArchived(id, isArchived)
    }

    override suspend fun moveToTrash(id: Long) = withContext(Dispatchers.IO) {
        savedItemDao.moveToTrash(id)
    }

    override suspend fun restoreFromTrash(id: Long) = withContext(Dispatchers.IO) {
        savedItemDao.restoreFromTrash(id)
    }

    override suspend fun permanentlyDelete(id: Long) = withContext(Dispatchers.IO) {
        val item = savedItemDao.getItemById(id)
        if (item != null) {
            fileStorageService.deleteFile(item.localFilePath)
            fileStorageService.deleteFile(item.thumbnailPath)
            savedItemFtsDao.delete(id)
            savedItemDao.permanentlyDelete(id)
        }
    }

    override suspend fun emptyTrash() = withContext(Dispatchers.IO) {
        val trashedItems = savedItemDao.getTrashedItemsList()
        for (item in trashedItems) {
            fileStorageService.deleteFile(item.localFilePath)
            fileStorageService.deleteFile(item.thumbnailPath)
            savedItemFtsDao.delete(item.id)
        }
        savedItemDao.emptyTrash()
        Unit
    }

    override suspend fun markOpened(id: Long) = withContext(Dispatchers.IO) {
        savedItemDao.updateLastOpened(id)
    }

    override suspend fun findByCanonicalUrl(canonicalUrl: String): SavedItem? = withContext(Dispatchers.IO) {
        savedItemDao.findByCanonicalUrl(canonicalUrl)?.toDomain()
    }

    override suspend fun findByTextHash(hash: String): SavedItem? = withContext(Dispatchers.IO) {
        savedItemDao.findByTextHash(hash)?.toDomain()
    }

    override suspend fun findByImageHash(sha256: String): SavedItem? = withContext(Dispatchers.IO) {
        savedItemDao.findByImageHash(sha256)?.toDomain()
    }

    override suspend fun addItemToCollection(itemId: Long, collectionId: Long) = withContext(Dispatchers.IO) {
        collectionDao.insertItemCollectionCrossRef(
            SavedItemCollectionCrossRef(savedItemId = itemId, collectionId = collectionId)
        )
    }

    override suspend fun removeItemFromCollection(itemId: Long, collectionId: Long) = withContext(Dispatchers.IO) {
        collectionDao.removeItemFromCollection(savedItemId = itemId, collectionId = collectionId)
    }

    override suspend fun setItemCollections(itemId: Long, collectionIds: List<Long>) = withContext(Dispatchers.IO) {
        collectionDao.clearCollectionsForSavedItem(itemId)
        for (cId in collectionIds) {
            collectionDao.insertItemCollectionCrossRef(
                SavedItemCollectionCrossRef(savedItemId = itemId, collectionId = cId)
            )
        }
    }

    private fun SavedItemEntity.toDomain(
        entities: List<ExtractedEntity> = emptyList(),
        tags: List<Tag> = emptyList(),
        collections: List<Collection> = emptyList()
    ) = SavedItem(
        id = id,
        contentType = contentType,
        title = title,
        description = description,
        originalUrl = originalUrl,
        canonicalUrl = canonicalUrl,
        sourceDomain = sourceDomain,
        sourceApp = sourceApp,
        mimeType = mimeType,
        localFilePath = localFilePath,
        thumbnailPath = thumbnailPath,
        originalText = originalText,
        extractedText = extractedText,
        ocrText = ocrText,
        comments = parseCommentsJson(commentsJson),
        createdAt = createdAt,
        updatedAt = updatedAt,
        lastOpenedAt = lastOpenedAt,
        isFavorite = isFavorite,
        isPinned = isPinned,
        isArchived = isArchived,
        isDeleted = isDeleted,
        processingStatus = processingStatus,
        userNote = userNote,
        captureNote = captureNote,
        entities = entities,
        tags = tags,
        collections = collections
    )

    private fun parseCommentsJson(json: String?): List<SavedComment> {
        if (json.isNullOrBlank()) return emptyList()
        return try {
            val array = org.json.JSONArray(json)
            val list = mutableListOf<SavedComment>()
            for (i in 0 until array.length()) {
                val obj = array.getJSONObject(i)
                val text = obj.optString("text", "")
                if (text.isNotBlank()) {
                    list.add(
                        SavedComment(
                            author = obj.optString("author", "User"),
                            text = text,
                            score = if (obj.has("score")) obj.optInt("score") else null,
                            timestamp = if (obj.has("timestamp")) obj.optLong("timestamp") else null
                        )
                    )
                }
            }
            list
        } catch (e: Exception) {
            emptyList()
        }
    }
}
