package com.tuck.app

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.tuck.app.data.local.db.TuckDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Runs MIGRATION_2_3 against a real SQLite database built from the checked-in v2
 * schema, then asserts that nothing was lost.
 *
 * This is the test that matters: `runMigrationsAndValidate` fails if the migrated
 * database does not match the v3 schema Room expects, which a mocked
 * SupportSQLiteDatabase cannot detect.
 */
@RunWith(AndroidJUnit4::class)
class TuckMigrationTest {

    private companion object {
        const val TEST_DB = "tuck-migration-test"

        val COMMENTS_JSON = """
            [
              {
                "id": "c1",
                "author": "u/alpha",
                "text": "Battery life is the biggest complaint",
                "score": 42,
                "replies": [
                  { "id": "c1a", "author": "u/beta", "text": "Agreed, mine lasts 4 hours", "score": 7 },
                  { "id": "c1b", "author": "u/gamma", "text": "Not on the newer revision", "score": 3 }
                ]
              },
              {
                "id": "c2",
                "author": "u/delta",
                "text": "Model A is the consensus pick",
                "score": 19
              }
            ]
        """.trimIndent()
    }

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        TuckDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    @Test
    fun migrate2To3_preservesItemsAndProducesValidV3Schema() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (1, 'URL', 'Best laptop under 80k?', 'A reddit thread',
                     'https://reddit.com/r/india/comments/abc', 'https://reddit.com/r/india/comments/abc',
                     'reddit.com', 'com.reddit.frontpage', NULL, NULL, NULL, NULL, NULL, NULL,
                     ?, 1700000000000, 1700000000000, NULL, 1, 0, 0, 'READY', 'hash-1', NULL)
                """.trimIndent(),
                arrayOf<Any?>(COMMENTS_JSON)
            )
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (2, 'IMAGE', 'Nike Air Max screenshot', NULL, NULL, NULL, NULL, 'com.android.gallery',
                     'image/png', '/data/user/0/com.tuck.app/files/img_2.png',
                     '/data/user/0/com.tuck.app/files/thumb_2.png', NULL, NULL, 'Nike Air Max 8999',
                     NULL, 1700000001000, 1700000001000, NULL, 0, 0, 0, 'READY', NULL, 'sha-2')
                """.trimIndent()
            )
            db.execSQL(
                "INSERT INTO collections (id, name, isAutoGenerated, icon, createdAt) VALUES (1, 'Shopping', 1, NULL, 1700000000000)"
            )
            db.execSQL(
                "INSERT INTO entities (id, savedItemId, type, value, normalizedValue) VALUES (1, 2, 'MONEY', '8999', '8999')"
            )
        }

        // Fails loudly if the migrated schema does not match 3.json.
        val db = helper.runMigrationsAndValidate(
            TEST_DB,
            3,
            true,
            TuckDatabase.MIGRATION_2_3
        )

        db.use {
            // Every source row survives.
            it.query("SELECT COUNT(*) FROM saved_items").use { c ->
                c.moveToFirst()
                assertEquals("both items must survive the migration", 2, c.getInt(0))
            }
            it.query("SELECT title, isFavorite, processingStatus FROM saved_items WHERE id = 1").use { c ->
                c.moveToFirst()
                assertEquals("Best laptop under 80k?", c.getString(0))
                assertEquals(1, c.getInt(1))
                assertEquals("READY", c.getString(2))
            }
            it.query("SELECT COUNT(*) FROM collections").use { c ->
                c.moveToFirst()
                assertEquals(1, c.getInt(0))
            }
            it.query("SELECT producer FROM entities WHERE id = 1").use { c ->
                c.moveToFirst()
                assertEquals("rule-based", c.getString(0))
            }

            // New columns land with their declared defaults.
            it.query("SELECT isPinned, openCount, deletedAt FROM saved_items WHERE id = 1").use { c ->
                c.moveToFirst()
                assertEquals(0, c.getInt(0))
                assertEquals(0, c.getInt(1))
                assertTrue("deletedAt should start null", c.isNull(2))
            }

            // localFilePath is promoted into media_assets.
            it.query("SELECT role, localPath, sha256 FROM media_assets WHERE itemId = 2").use { c ->
                assertTrue("item 2 must have a media asset", c.moveToFirst())
                assertEquals("PRIMARY", c.getString(0))
                assertEquals("/data/user/0/com.tuck.app/files/img_2.png", c.getString(1))
                assertEquals("sha-2", c.getString(2))
            }
            it.query("SELECT COUNT(*) FROM media_assets WHERE itemId = 1").use { c ->
                c.moveToFirst()
                assertEquals("an item with no file must not get an asset row", 0, c.getInt(0))
            }
        }
    }

    @Test
    fun migrate3To4_rebuildsSearchableRankedIndex() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (1, 'IMAGE', 'Nike Air Max screenshot', NULL, NULL, NULL, NULL, NULL, 'image/png',
                     NULL, NULL, NULL, NULL, 'Nike Air Max 8999 Amazon', NULL,
                     1700000000000, 1700000000000, NULL, 0, 0, 0, 'READY', NULL, NULL)
                """.trimIndent()
            )
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (2, 'NOTE', 'Deleted note', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                     'nike mentioned here', NULL, NULL, NULL,
                     1700000000000, 1700000000000, NULL, 0, 0, 1, 'READY', NULL, NULL)
                """.trimIndent()
            )
        }

        helper.runMigrationsAndValidate(TEST_DB, 3, true, TuckDatabase.MIGRATION_2_3).close()
        // validateDroppedTables = false: saved_items_fts is deliberately not a Room
        // entity, so Room reports it as an "unexpected table".
        val db = helper.runMigrationsAndValidate(TEST_DB, 4, false, TuckDatabase.MIGRATION_3_4)

        db.use {
            it.query("SELECT rowid FROM saved_items_fts WHERE saved_items_fts MATCH '\"nike\"*'").use { c ->
                assertEquals("only the live item is indexed", 1, c.count)
                c.moveToFirst()
                assertEquals(1L, c.getLong(0))
            }
            // matchinfo is what the ranking reads; assert it is queryable post-migration.
            it.query(
                "SELECT matchinfo(saved_items_fts, 'pcnalx') FROM saved_items_fts WHERE saved_items_fts MATCH '\"nike\"*'"
            ).use { c ->
                assertTrue("matchinfo must be available", c.moveToFirst())
                assertTrue("matchinfo returns a packed int blob", c.getBlob(0).size >= 12)
            }
            // The delete trigger keeps the index from stranding rows.
            it.execSQL("DELETE FROM saved_items WHERE id = 1")
            it.query("SELECT COUNT(*) FROM saved_items_fts").use { c ->
                c.moveToFirst()
                assertEquals("delete trigger must clear the index row", 0, c.getInt(0))
            }
        }
    }

    @Test
    fun migrate4To5_addsCapturedAtWithoutDisturbingExistingRows() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (1, 'IMAGE', 'Holiday photo', NULL, NULL, NULL, NULL, NULL, 'image/jpeg',
                     '/data/img_1.jpg', NULL, NULL, NULL, NULL, NULL,
                     1700000000000, 1700000000000, NULL, 0, 0, 0, 'READY', NULL, 'sha-1')
                """.trimIndent()
            )
        }

        helper.runMigrationsAndValidate(TEST_DB, 3, true, TuckDatabase.MIGRATION_2_3).close()
        helper.runMigrationsAndValidate(TEST_DB, 4, false, TuckDatabase.MIGRATION_3_4).close()
        val db = helper.runMigrationsAndValidate(TEST_DB, 5, false, TuckDatabase.MIGRATION_4_5)

        db.use {
            it.query("SELECT title, createdAt, capturedAt FROM saved_items WHERE id = 1").use { c ->
                assertTrue(c.moveToFirst())
                assertEquals("existing rows survive", "Holiday photo", c.getString(0))
                assertEquals("save time is untouched", 1700000000000L, c.getLong(1))
                assertTrue("capturedAt starts null, to be backfilled from EXIF", c.isNull(2))
            }
            // A pre-v5 row must accept a capture time without any further migration.
            it.execSQL("UPDATE saved_items SET capturedAt = 1500000000000 WHERE id = 1")
            it.query("SELECT capturedAt FROM saved_items WHERE id = 1").use { c ->
                c.moveToFirst()
                assertEquals(1500000000000L, c.getLong(0))
            }
        }
    }

    @Test
    fun migrate5To6_addsLifecycleColumnsAndKeepsExistingData() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (1, 'URL', 'Compare laptops', NULL, 'https://example.com', NULL, 'example.com',
                     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                     1700000000000, 1700000000000, NULL, 0, 0, 0, 'READY', NULL, NULL)
                """.trimIndent()
            )
        }

        helper.runMigrationsAndValidate(TEST_DB, 3, true, TuckDatabase.MIGRATION_2_3).close()
        helper.runMigrationsAndValidate(TEST_DB, 4, false, TuckDatabase.MIGRATION_3_4).close()
        helper.runMigrationsAndValidate(TEST_DB, 5, false, TuckDatabase.MIGRATION_4_5).close()
        val db = helper.runMigrationsAndValidate(TEST_DB, 6, false, TuckDatabase.MIGRATION_5_6)

        db.use {
            it.query("SELECT title, remindAt, completedAt FROM saved_items WHERE id = 1").use { c ->
                assertTrue(c.moveToFirst())
                assertEquals("Compare laptops", c.getString(0))
                assertTrue("an existing item has no reminder", c.isNull(1))
                assertTrue("an existing item is not marked done", c.isNull(2))
            }
            it.execSQL("UPDATE saved_items SET remindAt = 1800000000000, completedAt = 1800000001000 WHERE id = 1")
            it.query("SELECT remindAt, completedAt FROM saved_items WHERE id = 1").use { c ->
                c.moveToFirst()
                assertEquals(1800000000000L, c.getLong(0))
                assertEquals(1800000001000L, c.getLong(1))
            }
        }
    }

    @Test
    fun migrate6To7_addsFilingRulesTiedToCollections() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                "INSERT INTO collections (id, name, isAutoGenerated, icon, createdAt) VALUES (5, 'Research', 0, NULL, 1700000000000)"
            )
        }

        helper.runMigrationsAndValidate(TEST_DB, 3, true, TuckDatabase.MIGRATION_2_3).close()
        helper.runMigrationsAndValidate(TEST_DB, 4, false, TuckDatabase.MIGRATION_3_4).close()
        helper.runMigrationsAndValidate(TEST_DB, 5, false, TuckDatabase.MIGRATION_4_5).close()
        helper.runMigrationsAndValidate(TEST_DB, 6, false, TuckDatabase.MIGRATION_5_6).close()
        val db = helper.runMigrationsAndValidate(TEST_DB, 7, false, TuckDatabase.MIGRATION_6_7)

        db.use {
            it.execSQL("PRAGMA foreign_keys = ON")
            it.execSQL(
                "INSERT INTO filing_rules (query, collectionId, isEnabled, sortOrdinal, matchCount, createdAt) " +
                    "VALUES ('source:reddit', 5, 1, 0, 0, 1700000000000)"
            )
            it.query("SELECT query, collectionId, isEnabled FROM filing_rules").use { c ->
                assertTrue(c.moveToFirst())
                assertEquals("source:reddit", c.getString(0))
                assertEquals(5L, c.getLong(1))
                assertEquals(1, c.getInt(2))
            }

            // Deleting the collection must take its rules with it, or the rule would file
            // into a collection that no longer exists.
            it.execSQL("DELETE FROM collections WHERE id = 5")
            it.query("SELECT COUNT(*) FROM filing_rules").use { c ->
                c.moveToFirst()
                assertEquals("rules cascade with their collection", 0, c.getInt(0))
            }
        }
    }

    @Test
    fun migrate2To3_parsesCommentsJsonIntoMaterializedPathTree() {
        helper.createDatabase(TEST_DB, 2).use { db ->
            db.execSQL(
                """
                INSERT INTO saved_items
                    (id, contentType, title, description, originalUrl, canonicalUrl, sourceDomain,
                     sourceApp, mimeType, localFilePath, thumbnailPath, originalText, extractedText,
                     ocrText, commentsJson, createdAt, updatedAt, lastOpenedAt, isFavorite,
                     isArchived, isDeleted, processingStatus, textHash, imageSha256)
                VALUES
                    (1, 'URL', 'Best laptop under 80k?', NULL,
                     'https://reddit.com/r/india/comments/abc', NULL, 'reddit.com', NULL, NULL,
                     NULL, NULL, NULL, NULL, NULL, ?, 1700000000000, 1700000000000, NULL,
                     0, 0, 0, 'READY', NULL, NULL)
                """.trimIndent(),
                arrayOf<Any?>(COMMENTS_JSON)
            )
        }

        val db = helper.runMigrationsAndValidate(TEST_DB, 3, true, TuckDatabase.MIGRATION_2_3)

        db.use {
            it.query("SELECT platform, title FROM source_posts WHERE itemId = 1").use { c ->
                assertTrue("a source_post row must be created", c.moveToFirst())
                assertEquals("REDDIT", c.getString(0))
                assertEquals("Best laptop under 80k?", c.getString(1))
            }

            // Two roots plus two replies, ordered by materialized path.
            it.query(
                "SELECT path, depth, authorHandle, bodyText, score FROM source_comments WHERE itemId = 1 ORDER BY path ASC"
            ).use { c ->
                assertEquals("4 comments expected (2 roots + 2 replies)", 4, c.count)

                c.moveToNext()
                assertEquals("0001", c.getString(0))
                assertEquals(0, c.getInt(1))
                assertEquals("u/alpha", c.getString(2))
                assertEquals("Battery life is the biggest complaint", c.getString(3))
                assertEquals(42, c.getInt(4))

                c.moveToNext()
                assertEquals("nested reply keeps its parent path prefix", "0001.0001", c.getString(0))
                assertEquals(1, c.getInt(1))
                assertEquals("u/beta", c.getString(2))

                c.moveToNext()
                assertEquals("0001.0002", c.getString(0))
                assertEquals(1, c.getInt(1))
                assertEquals("u/gamma", c.getString(2))

                c.moveToNext()
                assertEquals("0002", c.getString(0))
                assertEquals(0, c.getInt(1))
                assertEquals("u/delta", c.getString(2))
            }

            // The original blob is preserved alongside the parsed tree.
            it.query("SELECT commentsJson FROM saved_items WHERE id = 1").use { c ->
                c.moveToFirst()
                assertNotNull("source blob must not be destroyed", c.getString(0))
            }
        }
    }
}
