package com.tuck.app.data.local.db.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "collections",
    indices = [
        Index(value = ["name"], unique = true),
        Index(value = ["isAutoGenerated"])
    ]
)
data class CollectionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val isAutoGenerated: Boolean = false,
    val icon: String? = null,
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(
    tableName = "saved_item_collections",
    primaryKeys = ["savedItemId", "collectionId"],
    foreignKeys = [
        ForeignKey(
            entity = SavedItemEntity::class,
            parentColumns = ["id"],
            childColumns = ["savedItemId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = CollectionEntity::class,
            parentColumns = ["id"],
            childColumns = ["collectionId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["savedItemId"]),
        Index(value = ["collectionId"])
    ]
)
data class SavedItemCollectionCrossRef(
    val savedItemId: Long,
    val collectionId: Long
)
