package com.tuck.app.ui.collections

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.tuck.app.domain.model.Collection
import com.tuck.app.domain.model.SavedItem
import com.tuck.app.domain.repository.CollectionRepository
import com.tuck.app.domain.repository.SavedItemRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

data class CollectionsUiState(
    val autoCollections: List<Collection> = emptyList(),
    val customCollections: List<Collection> = emptyList(),
    val selectedCollection: Collection? = null,
    val collectionItems: List<SavedItem> = emptyList(),
    val isCreatingCollection: Boolean = false
)

@HiltViewModel
class CollectionsViewModel @Inject constructor(
    private val collectionRepository: CollectionRepository,
    private val savedItemRepository: SavedItemRepository
) : ViewModel() {

    private val _selectedCollection = MutableStateFlow<Collection?>(null)
    private val _isCreating = MutableStateFlow(false)

    init {
        viewModelScope.launch {
            collectionRepository.ensureDefaultCollections()
        }
    }

    private val collectionItemsFlow = _selectedCollection.flatMapLatest { col ->
        if (col == null) {
            flowOf(emptyList())
        } else {
            savedItemRepository.getItemsByCollection(col.id)
        }
    }

    val uiState: StateFlow<CollectionsUiState> = combine(
        collectionRepository.getAutoGeneratedCollections(),
        collectionRepository.getCustomCollections(),
        _selectedCollection,
        collectionItemsFlow,
        _isCreating
    ) { autoCols, customCols, selected, items, isCreating ->
        CollectionsUiState(
            autoCollections = autoCols,
            customCollections = customCols,
            selectedCollection = selected,
            collectionItems = items,
            isCreatingCollection = isCreating
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = CollectionsUiState()
    )

    fun selectCollection(collection: Collection?) {
        _selectedCollection.value = collection
    }

    fun showCreateDialog(show: Boolean) {
        _isCreating.value = show
    }

    fun createCollection(name: String) {
        val trimmed = name.trim()
        if (trimmed.isNotBlank()) {
            viewModelScope.launch {
                collectionRepository.createCollection(trimmed, isAutoGenerated = false)
                _isCreating.value = false
            }
        }
    }

    fun deleteCollection(collectionId: Long) {
        viewModelScope.launch {
            collectionRepository.deleteCollection(collectionId)
            if (_selectedCollection.value?.id == collectionId) {
                _selectedCollection.value = null
            }
        }
    }

    fun toggleFavorite(itemId: Long, current: Boolean) {
        viewModelScope.launch {
            savedItemRepository.setFavorite(itemId, !current)
        }
    }
}
