package com.tuck.app.domain.model

data class ExtractedEntity(
    val id: Long = 0,
    val savedItemId: Long,
    val type: EntityType,
    val value: String,
    val normalizedValue: String
)

data class Tag(
    val id: Long = 0,
    val name: String
)

data class Collection(
    val id: Long = 0,
    val name: String,
    val isAutoGenerated: Boolean = false,
    val icon: String? = null,
    val color: String? = null,
    val isLocked: Boolean = false,
    val itemCount: Int = 0,
    val createdAt: Long = System.currentTimeMillis()
)

