package com.tuck.app.domain.model

data class ExtractedEntity(
    val id: Long = 0,
    val savedItemId: Long,
    val type: EntityType,
    val value: String,
    val normalizedValue: String
)

data class Tag(
    val id: Long = 0,
    val name: String
)

data class Collection(
    val id: Long = 0,
    val name: String,
    val isAutoGenerated: Boolean = false,
    val icon: String? = null,
    val color: String? = null,
    val isLocked: Boolean = false,
    val itemCount: Int = 0,
    /** Items still outstanding, i.e. not marked done. */
    val openCount: Int = 0,
    /** Newest preview images, for the tile composition. Empty means show the colour tile. */
    val previewPaths: List<String> = emptyList(),
    val createdAt: Long = System.currentTimeMillis()
)

