package com.tuck.app.data.local.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.tuck.app.data.local.db.entity.CollectionEntity
import com.tuck.app.data.local.db.entity.SavedItemCollectionCrossRef
import kotlinx.coroutines.flow.Flow

data class CollectionWithCount(
    val id: Long,
    val name: String,
    val isAutoGenerated: Boolean,
    val icon: String?,
    val createdAt: Long,
    val itemCount: Int
)

@Dao
interface CollectionDao {
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insert(collection: CollectionEntity): Long

    @Update
    suspend fun update(collection: CollectionEntity)

    @Query("SELECT * FROM collections WHERE id = :id LIMIT 1")
    suspend fun getById(id: Long): CollectionEntity?

    @Query("SELECT * FROM collections WHERE name = :name LIMIT 1")
    suspend fun getByName(name: String): CollectionEntity?

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.createdAt,
               COUNT(s.id) AS itemCount
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        GROUP BY c.id
        ORDER BY c.isAutoGenerated ASC, c.name ASC
    """)
    fun getAllCollectionsWithCount(): Flow<List<CollectionWithCount>>

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.createdAt,
               COUNT(s.id) AS itemCount
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        WHERE c.isAutoGenerated = 1
        GROUP BY c.id
        ORDER BY c.name ASC
    """)
    fun getAutoGeneratedCollectionsWithCount(): Flow<List<CollectionWithCount>>

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.createdAt,
               COUNT(s.id) AS itemCount
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        WHERE c.isAutoGenerated = 0
        GROUP BY c.id
        ORDER BY c.name ASC
    """)
    fun getCustomCollectionsWithCount(): Flow<List<CollectionWithCount>>

    @Query("""
        SELECT c.* FROM collections c
        INNER JOIN saved_item_collections sc ON c.id = sc.collectionId
        WHERE sc.savedItemId = :savedItemId
    """)
    suspend fun getCollectionsForSavedItem(savedItemId: Long): List<CollectionEntity>

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertItemCollectionCrossRef(crossRef: SavedItemCollectionCrossRef)

    @Query("DELETE FROM saved_item_collections WHERE savedItemId = :savedItemId AND collectionId = :collectionId")
    suspend fun removeItemFromCollection(savedItemId: Long, collectionId: Long)

    @Query("DELETE FROM saved_item_collections WHERE savedItemId = :savedItemId")
    suspend fun clearCollectionsForSavedItem(savedItemId: Long)

    @Query("DELETE FROM collections WHERE id = :id")
    suspend fun deleteCollection(id: Long)

    @Query("SELECT COUNT(*) FROM collections")
    suspend fun getCollectionCount(): Int
}
