package com.tuck.app.data.local.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.tuck.app.data.local.db.entity.CollectionEntity
import com.tuck.app.data.local.db.entity.SavedItemCollectionCrossRef
import kotlinx.coroutines.flow.Flow

data class CollectionWithCount(
    val id: Long,
    val name: String,
    val isAutoGenerated: Boolean,
    val icon: String?,
    val color: String? = null,
    val isLocked: Boolean = false,
    val createdAt: Long,
    val itemCount: Int,
    /** Items still outstanding - completedAt is null. Drives "12 to read". */
    val openCount: Int = 0,
    /** Newest thumbnails in the collection, for the tile preview. */
    val previewPaths: String? = null
)

/** One collection's preview thumbnails, newest first. */
data class CollectionPreview(
    val collectionId: Long,
    val path: String
)

@Dao
interface CollectionDao {
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insert(collection: CollectionEntity): Long

    @Update
    suspend fun update(collection: CollectionEntity)

    @Query("SELECT * FROM collections WHERE id = :id LIMIT 1")
    suspend fun getById(id: Long): CollectionEntity?

    @Query("SELECT * FROM collections WHERE name = :name LIMIT 1")
    suspend fun getByName(name: String): CollectionEntity?

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.color, c.isLocked, c.createdAt,
               COUNT(s.id) AS itemCount,
               COALESCE(SUM(CASE WHEN s.id IS NOT NULL AND s.completedAt IS NULL THEN 1 ELSE 0 END), 0) AS openCount,
               NULL AS previewPaths
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        GROUP BY c.id
        ORDER BY itemCount DESC, c.name ASC
    """)
    fun getAllCollectionsWithCount(): Flow<List<CollectionWithCount>>

    /**
     * Up to [perCollection] preview images per collection, newest first.
     *
     * Top-N-per-group without a window function - Room's SQL parser rejects
     * ROW_NUMBER() OVER - by counting how many newer previewable items the same
     * collection has. One query for the whole grid rather than one per tile.
     */
    @Query("""
        SELECT sc.collectionId AS collectionId,
               COALESCE(s.thumbnailPath, s.localFilePath) AS path
        FROM saved_item_collections sc
        JOIN saved_items s ON sc.savedItemId = s.id
        WHERE s.isDeleted = 0 AND s.isArchived = 0
          AND COALESCE(s.thumbnailPath, s.localFilePath) IS NOT NULL
          AND COALESCE(s.thumbnailPath, s.localFilePath) != ''
          AND (
            SELECT COUNT(*)
            FROM saved_item_collections sc2
            JOIN saved_items s2 ON sc2.savedItemId = s2.id
            WHERE sc2.collectionId = sc.collectionId
              AND s2.isDeleted = 0 AND s2.isArchived = 0
              AND COALESCE(s2.thumbnailPath, s2.localFilePath) IS NOT NULL
              AND COALESCE(s2.thumbnailPath, s2.localFilePath) != ''
              AND s2.createdAt > s.createdAt
          ) < :perCollection
        ORDER BY sc.collectionId ASC, s.createdAt DESC
    """)
    fun getCollectionPreviews(perCollection: Int): Flow<List<CollectionPreview>>

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.color, c.isLocked, c.createdAt,
               COUNT(s.id) AS itemCount,
               COALESCE(SUM(CASE WHEN s.id IS NOT NULL AND s.completedAt IS NULL THEN 1 ELSE 0 END), 0) AS openCount,
               NULL AS previewPaths
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        WHERE c.isAutoGenerated = 1
        GROUP BY c.id
        ORDER BY itemCount DESC, c.name ASC
    """)
    fun getAutoGeneratedCollectionsWithCount(): Flow<List<CollectionWithCount>>

    @Query("""
        SELECT c.id, c.name, c.isAutoGenerated, c.icon, c.color, c.isLocked, c.createdAt,
               COUNT(s.id) AS itemCount,
               COALESCE(SUM(CASE WHEN s.id IS NOT NULL AND s.completedAt IS NULL THEN 1 ELSE 0 END), 0) AS openCount,
               NULL AS previewPaths
        FROM collections c
        LEFT JOIN saved_item_collections sc ON c.id = sc.collectionId
        LEFT JOIN saved_items s ON sc.savedItemId = s.id AND s.isDeleted = 0 AND s.isArchived = 0
        WHERE c.isAutoGenerated = 0
        GROUP BY c.id
        ORDER BY itemCount DESC, c.name ASC
    """)
    fun getCustomCollectionsWithCount(): Flow<List<CollectionWithCount>>

    @Query("""
        SELECT c.* FROM collections c
        INNER JOIN saved_item_collections sc ON c.id = sc.collectionId
        WHERE sc.savedItemId = :savedItemId
    """)
    suspend fun getCollectionsForSavedItem(savedItemId: Long): List<CollectionEntity>

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertItemCollectionCrossRef(crossRef: SavedItemCollectionCrossRef)

    @Query("DELETE FROM saved_item_collections WHERE savedItemId = :savedItemId AND collectionId = :collectionId")
    suspend fun removeItemFromCollection(savedItemId: Long, collectionId: Long)

    @Query("DELETE FROM saved_item_collections WHERE savedItemId = :savedItemId")
    suspend fun clearCollectionsForSavedItem(savedItemId: Long)

    @Query("DELETE FROM collections WHERE id = :id")
    suspend fun deleteCollection(id: Long)

    @Query("SELECT COUNT(*) FROM collections")
    suspend fun getCollectionCount(): Int
}
