package com.tuck.app.domain.repository

import com.tuck.app.domain.model.Collection
import kotlinx.coroutines.flow.Flow

interface CollectionRepository {
    fun getAllCollections(): Flow<List<Collection>>
    fun getAutoGeneratedCollections(): Flow<List<Collection>>
    fun getCustomCollections(): Flow<List<Collection>>
    suspend fun getCollectionById(id: Long): Collection?
    suspend fun getCollectionByName(name: String): Collection?
    suspend fun createCollection(name: String, isAutoGenerated: Boolean = false, icon: String? = null, color: String? = null): Long
    suspend fun updateCollectionColor(id: Long, color: String?)
    suspend fun renameCollection(id: Long, newName: String)
    suspend fun deleteCollection(id: Long)
    suspend fun ensureDefaultCollections()
}
